- hosts: localhost
  become: false
  tasks:
    - name: Clean Dock to only show active apps
      shell: defaults write com.apple.dock static-only -bool TRUE; killall Dock
      tags:
        - clean-dock
# To get your old dock back, simply change “TRUE” to “FALSE”. Note that the “killall Dock” segment of the command is used to restart the Dock and activate your changes. If you’re going to use this, you’ll probably want to disable Show indicators for open applications under System Preferences > Dock & Menu Bar.