- hosts: localhost
  become: true
  vars:
    source_key: "../.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    source_key_config: "../.ssh/config"
    dest_key_config: "{{ lookup('env', 'HOME') }}/.ssh/config"
  tasks:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory
      tags:
        - dotfiles
        - install
        - ssh
    - name: Install ssh key (private)
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        owner: puribey
        group: staff
        mode: 0600
      tags:
        - dotfiles
        - install
        - ssh
    - name: Install ssh key (public)
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        owner: puribey
        group: staff
        mode: 0600
      tags:
        - dotfiles
        - install
        - ssh
