- hosts: localhost
  become: false
  tasks:
    - name: Create ~/Documents/Classdojo/Repos
      shell: cd ~/Documents/Classdojo && mkdir -p ~/Documents/Classdojo/Repos
      tags:
        - install
        - classdojo-project
    - name: ClassDojo - api
      ansible.builtin.git:
        repo: "git@github.com:classdojo/api.git"
        dest: "{{ lookup('env', 'HOME')}}/Documents/Classdojo/Repos/api"
        bare: false
      tags:
        - install
        - classdojo-project
    - name: ClassDojo - Web-Monorepo
      ansible.builtin.git:
        repo: "git@github.com:classdojo/web-monorepo.git"
        dest: "{{ lookup('env', 'HOME')}}/Documents/Classdojo/Repos/web-monorepo"
        bare: false
      tags:
        - install
        - classdojo-project
    # - name: ClassDojo - logs.classdojo.com
    #   ansible.builtin.git:
    #     repo: "git@github.com:classdojo/logs.classdojo.com.git"
    #     dest: "{{ lookup('env', 'HOME')}}/Documents/Classdojo/Repos/logs.classdojo.com"
    #     bare: false
    #   tags:
    #     - install
    #     - classdojo-project
    # - name: ClassDojo - nomad-system-jobs
    #   ansible.builtin.git:
    #     repo: "git@github.com:classdojo/nomad-system-jobs.git"
    #     dest: "{{ lookup('env', 'HOME')}}/Documents/Classdojo/Repos/nomad-system-jobs"
    #     bare: false
    #   tags:
    #     - install
    #     - classdojo-project
    # - name: ClassDojo - terraform-infra
    #   ansible.builtin.git:
    #     repo: "git@github.com:classdojo/terraform-infra.git"
    #     dest: "{{ lookup('env', 'HOME')}}/Documents/Classdojo/Repos/terraform-infra"
    #     bare: false
    #   tags:
    #     - install
    #     - classdojo-project
    # - name: ClassDojo - generate-haproxy-cfg
    #   ansible.builtin.git:
    #     repo: "git@github.com:classdojo/generate-haproxy-cfg.git"
    #     dest: "{{ lookup('env', 'HOME')}}/Documents/Classdojo/Repos/generate-haproxy-cfg"
    #     bare: false
    #   tags:
    #     - install
    #     - classdojo-project
    # - name: ClassDojo - mojo-and-friends
    #   ansible.builtin.git:
    #     repo: "git@github.com:classdojo/mojo-and-friends.git"
    #     dest: "{{ lookup('env', 'HOME')}}/Documents/Classdojo/Repos/mojo-and-friends"
    #     bare: false
    #   tags:
    #     - install
    #     - classdojo-project
